/* AUTO-GENERATED by tools/gen_stubs.py -- do not edit. */
/* Source manifest: /tmp/iwork_union_manifest.json */

#import <Foundation/Foundation.h>
#import <AppKit/AppKit.h>
#import <CoreFoundation/CoreFoundation.h>

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wincomplete-implementation"
#pragma clang diagnostic ignored "-Wobjc-root-class"

/* ---- empty class stubs ---- */

@interface CKContainer : NSObject @end
@implementation CKContainer @end
@interface NSFileAccessIntent : NSObject @end
@implementation NSFileAccessIntent @end
@interface NSURLQueryItem : NSObject @end
@implementation NSURLQueryItem @end
@interface NSAccessibilityElement : NSObject @end
@implementation NSAccessibilityElement @end
@interface NSSplitViewItem : NSObject @end
@implementation NSSplitViewItem @end
@interface NSSplitViewController : NSObject @end
@implementation NSSplitViewController @end

/* ---- NSString_const ---- */

NSString * const CKErrorDomain = @"CKErrorDomain";
NSString * const CKErrorRetryAfterKey = @"CKErrorRetryAfterKey";
NSString * const MLMediaSourcePhotosIdentifier = @"MLMediaSourcePhotosIdentifier";
NSString * const MLPhotosAlbumTypeIdentifier = @"MLPhotosAlbumTypeIdentifier";
NSString * const MLPhotosAlbumsGroupTypeIdentifier = @"MLPhotosAlbumsGroupTypeIdentifier";
NSString * const MLPhotosAllPhotosAlbumTypeIdentifier = @"MLPhotosAllPhotosAlbumTypeIdentifier";
NSString * const MLPhotosCollectionGroupTypeIdentifier = @"MLPhotosCollectionGroupTypeIdentifier";
NSString * const MLPhotosFacesAlbumTypeIdentifier = @"MLPhotosFacesAlbumTypeIdentifier";
NSString * const MLPhotosFavoritesGroupTypeIdentifier = @"MLPhotosFavoritesGroupTypeIdentifier";
NSString * const MLPhotosLastImportGroupTypeIdentifier = @"MLPhotosLastImportGroupTypeIdentifier";
NSString * const MLPhotosMomentGroupTypeIdentifier = @"MLPhotosMomentGroupTypeIdentifier";
NSString * const MLPhotosMyPhotoStreamTypeIdentifier = @"MLPhotosMyPhotoStreamTypeIdentifier";
NSString * const MLPhotosPanoramasGroupTypeIdentifier = @"MLPhotosPanoramasGroupTypeIdentifier";
NSString * const MLPhotosPublishedAlbumTypeIdentifier = @"MLPhotosPublishedAlbumTypeIdentifier";
NSString * const MLPhotosSharedGroupTypeIdentifier = @"MLPhotosSharedGroupTypeIdentifier";
NSString * const MLPhotosSharedPhotoStreamTypeIdentifier = @"MLPhotosSharedPhotoStreamTypeIdentifier";
NSString * const MLPhotosSmartAlbumTypeIdentifier = @"MLPhotosSmartAlbumTypeIdentifier";
NSString * const MLPhotosYearGroupTypeIdentifier = @"MLPhotosYearGroupTypeIdentifier";
NSString * const NSMetadataQueryAccessibleUbiquitousExternalDocumentsScope = @"NSMetadataQueryAccessibleUbiquitousExternalDocumentsScope";
NSString * const NSStringEncodingDetectionFromWindowsKey = @"NSStringEncodingDetectionFromWindowsKey";
NSString * const NSStringEncodingDetectionSuggestedEncodingsKey = @"NSStringEncodingDetectionSuggestedEncodingsKey";
NSString * const NSPopoverCloseReasonUserInfoKey = @"NSPopoverCloseReasonUserInfoKey";
NSString * const NSUserActivityDocumentURLKey = @"NSUserActivityDocumentURLKey";
NSString * const NSURLDocumentIdentifierKey = @"NSURLDocumentIdentifierKey";

/* ---- c_string_const ---- */

const char * const kOSThermalNotificationPressureLevelName = "kOSThermalNotificationPressureLevelName";

/* ---- unknown ---- */

void *NSSplitViewItemUnspecifiedDimension = (void *)0;

#pragma clang diagnostic pop
