#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
gen_stubs.py <classified_manifest.json> [--out <kpf_auto_stubs.m>] [--skip <manual_symbols.txt>]

Reads the *classified* manifest produced by classify_symbols.py and emits
typed Objective-C stub definitions per symbol.

kind dispatch
  NSString_const    -> NSString * const X = @"X";
  CFString_const    -> CFStringRef const X = CFSTR("X");
  c_string_const    -> const char * const X = "X";
  CGFloat           -> const CGFloat X = 0.0;
  NSEdgeInsets      -> const NSEdgeInsets X = {0, 0, 0, 0};
  objc_class        -> @interface X : NSObject @end @implementation X @end
  function          -> SKIPPED (functions need a hand-written body in
                       kpf_stubs.m -- the script lists them so the human
                       knows what to write)
  data_unknown      -> void *X = (void *)0;  (8-byte zero slot)
  unknown           -> void *X = (void *)0;

Symbols listed in <manual_symbols.txt> are skipped regardless of kind --
they are provided by the hand-tuned kpf_stubs.m.
"""
import sys, json, re


EMITTERS = {
    'NSString_const': lambda name: 'NSString * const %s = @"%s";' % (name, name),
    'CFString_const': lambda name: 'CFStringRef const %s = CFSTR("%s");' % (name, name),
    'c_string_const': lambda name: 'const char * const %s = "%s";' % (name, name),
    'CGFloat':        lambda name: 'const CGFloat %s = 0.0;' % name,
    'NSEdgeInsets':   lambda name: 'const NSEdgeInsets %s = {0, 0, 0, 0};' % name,
    'data_unknown':   lambda name: 'void *%s = (void *)0;' % name,
    'unknown':        lambda name: 'void *%s = (void *)0;' % name,
}


def main():
    if len(sys.argv) < 2:
        print(__doc__); sys.exit(1)
    manifest_path = sys.argv[1]
    out_path = sys.argv[sys.argv.index('--out') + 1] if '--out' in sys.argv else 'stubs/kpf_auto_stubs.m'
    skip_path = sys.argv[sys.argv.index('--skip') + 1] if '--skip' in sys.argv else None

    with open(manifest_path) as f:
        manifest = json.load(f)

    skipped = set()
    if skip_path:
        with open(skip_path) as f:
            for line in f:
                line = line.split('#', 1)[0].strip()
                if line:
                    skipped.add(line)

    classes_done = set()
    data_lines_by_kind = {}
    class_lines = []
    skipped_functions = []
    skipped_manual = []

    for entry in manifest['missing_symbols']:
        sym = entry['symbol']
        if sym in skipped:
            skipped_manual.append(sym)
            continue
        kind = entry.get('kind', 'unknown')
        if kind == 'objc_class':
            m = re.match(r'^_OBJC_(?:META)?CLASS_\$_(.+)$', sym)
            if not m:
                continue
            cls = m.group(1)
            if cls in classes_done:
                continue
            classes_done.add(cls)
            class_lines.append("@interface %s : NSObject @end" % cls)
            class_lines.append("@implementation %s @end" % cls)
            continue
        if kind == 'function':
            skipped_functions.append(sym)
            continue
        emitter = EMITTERS.get(kind, EMITTERS['unknown'])
        # Strip leading underscore for C source -- linker adds it back.
        c_name = sym.lstrip('_')
        data_lines_by_kind.setdefault(kind, []).append(emitter(c_name))

    with open(out_path, 'w') as f:
        f.write("/* AUTO-GENERATED by tools/gen_stubs.py -- do not edit. */\n")
        f.write("/* Source manifest: %s */\n\n" % manifest_path)
        # Importing AppKit / framework umbrellas pulls in the real
        # decls of the constants we're stubbing -- compiling against a
        # newer SDK then errors out with `redefinition of X with a
        # different type` (e.g. `NSPasteboardName const X` vs our
        # `NSString *const X`). Stick to Foundation + CoreFoundation,
        # which give us NSString * / CFStringRef / NSObject without
        # the conflicting decls.
        f.write("#import <Foundation/Foundation.h>\n")
        f.write("#import <CoreFoundation/CoreFoundation.h>\n")
        f.write("#import <CoreGraphics/CoreGraphics.h>  // CGFloat\n\n")
        f.write("#pragma clang diagnostic push\n")
        f.write('#pragma clang diagnostic ignored "-Wincomplete-implementation"\n')
        f.write('#pragma clang diagnostic ignored "-Wobjc-root-class"\n\n')
        if class_lines:
            f.write("/* ---- empty class stubs ---- */\n\n")
            for line in class_lines:
                f.write(line + "\n")
            f.write("\n")
        for kind, lines in sorted(data_lines_by_kind.items()):
            f.write("/* ---- %s ---- */\n\n" % kind)
            for line in lines:
                f.write(line + "\n")
            f.write("\n")
        f.write("#pragma clang diagnostic pop\n")

    print("wrote %s:" % out_path)
    print("  classes: %d" % len(classes_done))
    for kind, lines in sorted(data_lines_by_kind.items()):
        print("  %s: %d" % (kind, len(lines)))
    print("  skipped (in manual_symbols.txt): %d" % len(skipped_manual))
    print("  skipped (functions -- need hand stubs in kpf_stubs.m): %d" % len(skipped_functions))
    if skipped_functions:
        print()
        print("  These function symbols still need implementations in kpf_stubs.m:")
        for s in skipped_functions:
            print("    %s" % s)


if __name__ == '__main__':
    main()
